version: "3"
# 도커 volume 연결
volumes:
  findUI-main-vol:
    # external true로 성정해야 docker volume의 데이터가 삭제 안됨
    external: true
    name: findUI-main-vol
services:
  db:
    image: mysql:8.0
    volumes:
      # container MySql과 docker volume 연결
      - findUI-main-vol:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: finedUI
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
      TZ: Asia/Seoul
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    restart: always
  server:
    # container 실행 순서 보장 (db -> server)
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Backend/findUI
    ports:
      - 8081:8080
    # container에 문제가 생겨 종료됐을때 자동 재시작 true
    restart: always
