ai:
#  서버용
  host: "http://aiserver:8000"
#  로컬 테스트용
#  host: "http://localhost:8000"
  search: "/api/search"
  create: "/api/regist"
  update: "/api/update"
  delete: "/api/delete"
  change: "/api/regist/change"