spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finedUI?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: ssafy
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: fined&youHikariPool
  jpa:
    defer-datasource-initialization: true
    database: mysql
    hibernate:
      ddl:
        auto: update
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

# security log level 설정
logging:
  level:
    org:
      springframework:
        security: DEBUG
# hibernate log level 설정

# 디버깅용 로그레벨 설정.



#  devtools의 기본옵션이 true.
#  devtools:
#    livereload:
#      enabled: true


