# DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Local
#    url: jdbc:mysql://localhost:3306/finedUI?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    # Dummy
    url : jdbc:mysql://j8a108.p.ssafy.io:3300/finedui?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ssafy
    password: ssafy
  jpa:
    defer-datasource-initialization: true
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      location: /Users/SSAFY/
      max-request-size: 30MB
      max-file-size: 10MB

# Image
image:
  upload:
    path: /Users/SSAFY/

# AWS S3
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: finedui-ajh
      base-path: chat_image/
    credentials:
      access-key: AKIA3WSTMVY35UWKIAXY
      secret-key: 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
    stack:
      auto: false

# AWS Error
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR